/* tslint:disable */
/* eslint-disable */
/**
 * GeoSearch
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.3.2
 * Contact: info@geosearch.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BatchRequest,
  CityListResponse,
  CountryListResponse,
  ErrorResponse,
  RegionListResponse,
} from '../models/index';
import {
    BatchRequestFromJSON,
    BatchRequestToJSON,
    CityListResponseFromJSON,
    CityListResponseToJSON,
    CountryListResponseFromJSON,
    CountryListResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    RegionListResponseFromJSON,
    RegionListResponseToJSON,
} from '../models/index';

export interface BatchCitiesRequest {
    batchRequest: BatchRequest;
    lang?: string;
    fields?: string;
}

export interface BatchCountriesRequest {
    batchRequest: BatchRequest;
    lang?: string;
    fields?: string;
}

export interface BatchRegionsRequest {
    batchRequest: BatchRequest;
    lang?: string;
    fields?: string;
}

/**
 * 
 */
export class BatchApi extends runtime.BaseAPI {

    /**
     * Creates request options for batchCities without sending the request
     */
    async batchCitiesRequestOpts(requestParameters: BatchCitiesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['batchRequest'] == null) {
            throw new runtime.RequiredError(
                'batchRequest',
                'Required parameter "batchRequest" was null or undefined when calling batchCities().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/batch/cities`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BatchRequestToJSON(requestParameters['batchRequest']),
        };
    }

    /**
     * Returns multiple cities in a single request. Maximum 50 IDs per request.
     * Batch lookup cities by IDs
     */
    async batchCitiesRaw(requestParameters: BatchCitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CityListResponse>> {
        const requestOptions = await this.batchCitiesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CityListResponseFromJSON(jsonValue));
    }

    /**
     * Returns multiple cities in a single request. Maximum 50 IDs per request.
     * Batch lookup cities by IDs
     */
    async batchCities(requestParameters: BatchCitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CityListResponse> {
        const response = await this.batchCitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for batchCountries without sending the request
     */
    async batchCountriesRequestOpts(requestParameters: BatchCountriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['batchRequest'] == null) {
            throw new runtime.RequiredError(
                'batchRequest',
                'Required parameter "batchRequest" was null or undefined when calling batchCountries().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/batch/countries`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BatchRequestToJSON(requestParameters['batchRequest']),
        };
    }

    /**
     * Returns multiple countries in a single request. Maximum 50 IDs per request.
     * Batch lookup countries by IDs
     */
    async batchCountriesRaw(requestParameters: BatchCountriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CountryListResponse>> {
        const requestOptions = await this.batchCountriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CountryListResponseFromJSON(jsonValue));
    }

    /**
     * Returns multiple countries in a single request. Maximum 50 IDs per request.
     * Batch lookup countries by IDs
     */
    async batchCountries(requestParameters: BatchCountriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CountryListResponse> {
        const response = await this.batchCountriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for batchRegions without sending the request
     */
    async batchRegionsRequestOpts(requestParameters: BatchRegionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['batchRequest'] == null) {
            throw new runtime.RequiredError(
                'batchRequest',
                'Required parameter "batchRequest" was null or undefined when calling batchRegions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/batch/regions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BatchRequestToJSON(requestParameters['batchRequest']),
        };
    }

    /**
     * Returns multiple regions in a single request. Maximum 50 IDs per request.
     * Batch lookup regions by IDs
     */
    async batchRegionsRaw(requestParameters: BatchRegionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegionListResponse>> {
        const requestOptions = await this.batchRegionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegionListResponseFromJSON(jsonValue));
    }

    /**
     * Returns multiple regions in a single request. Maximum 50 IDs per request.
     * Batch lookup regions by IDs
     */
    async batchRegions(requestParameters: BatchRegionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegionListResponse> {
        const response = await this.batchRegionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
