/* tslint:disable */
/* eslint-disable */
/**
 * GeoSearch
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.3.2
 * Contact: info@geosearch.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CityListResponse,
  CitySingleResponse,
  ErrorResponse,
  HierarchyListResponse,
  NearbyCityListResponse,
} from '../models/index';
import {
    CityListResponseFromJSON,
    CityListResponseToJSON,
    CitySingleResponseFromJSON,
    CitySingleResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HierarchyListResponseFromJSON,
    HierarchyListResponseToJSON,
    NearbyCityListResponseFromJSON,
    NearbyCityListResponseToJSON,
} from '../models/index';

export interface CityHierarchyRequest {
    id: number;
    lang?: string;
}

export interface GetCityRequest {
    id: number;
    lang?: string;
    fields?: string;
}

export interface ListCitiesRequest {
    lang?: string;
    country?: string;
    admin1?: string;
    name?: string;
    populationMin?: number;
    populationMax?: number;
    timezone?: string;
    minElevation?: number;
    maxElevation?: number;
    within?: number;
    bbox?: string;
    cursor?: string;
    limit?: number;
    fields?: string;
    sort?: string;
}

export interface NearbyCitiesRequest {
    lat: number;
    lon: number;
    radius?: number;
    limit?: number;
    fields?: string;
}

/**
 * 
 */
export class CitiesApi extends runtime.BaseAPI {

    /**
     * Creates request options for cityHierarchy without sending the request
     */
    async cityHierarchyRequestOpts(requestParameters: CityHierarchyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cityHierarchy().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/cities/{id}/hierarchy`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the full administrative hierarchy for a city, ordered from the city itself up through region, country, and continent. 
     * Get administrative hierarchy for a city
     */
    async cityHierarchyRaw(requestParameters: CityHierarchyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HierarchyListResponse>> {
        const requestOptions = await this.cityHierarchyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HierarchyListResponseFromJSON(jsonValue));
    }

    /**
     * Returns the full administrative hierarchy for a city, ordered from the city itself up through region, country, and continent. 
     * Get administrative hierarchy for a city
     */
    async cityHierarchy(requestParameters: CityHierarchyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HierarchyListResponse> {
        const response = await this.cityHierarchyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCity without sending the request
     */
    async getCityRequestOpts(requestParameters: GetCityRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCity().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/cities/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a single city by its numeric ID.
     * Get city by ID
     */
    async getCityRaw(requestParameters: GetCityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CitySingleResponse>> {
        const requestOptions = await this.getCityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CitySingleResponseFromJSON(jsonValue));
    }

    /**
     * Returns a single city by its numeric ID.
     * Get city by ID
     */
    async getCity(requestParameters: GetCityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CitySingleResponse> {
        const response = await this.getCityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCities without sending the request
     */
    async listCitiesRequestOpts(requestParameters: ListCitiesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['country'] != null) {
            queryParameters['country'] = requestParameters['country'];
        }

        if (requestParameters['admin1'] != null) {
            queryParameters['admin1'] = requestParameters['admin1'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['populationMin'] != null) {
            queryParameters['population_min'] = requestParameters['populationMin'];
        }

        if (requestParameters['populationMax'] != null) {
            queryParameters['population_max'] = requestParameters['populationMax'];
        }

        if (requestParameters['timezone'] != null) {
            queryParameters['timezone'] = requestParameters['timezone'];
        }

        if (requestParameters['minElevation'] != null) {
            queryParameters['min_elevation'] = requestParameters['minElevation'];
        }

        if (requestParameters['maxElevation'] != null) {
            queryParameters['max_elevation'] = requestParameters['maxElevation'];
        }

        if (requestParameters['within'] != null) {
            queryParameters['within'] = requestParameters['within'];
        }

        if (requestParameters['bbox'] != null) {
            queryParameters['bbox'] = requestParameters['bbox'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/cities`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a paginated list of cities with optional filtering by country, admin code, name, population, timezone, and elevation.
     * List cities
     */
    async listCitiesRaw(requestParameters: ListCitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CityListResponse>> {
        const requestOptions = await this.listCitiesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CityListResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of cities with optional filtering by country, admin code, name, population, timezone, and elevation.
     * List cities
     */
    async listCities(requestParameters: ListCitiesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CityListResponse> {
        const response = await this.listCitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for nearbyCities without sending the request
     */
    async nearbyCitiesRequestOpts(requestParameters: NearbyCitiesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['lat'] == null) {
            throw new runtime.RequiredError(
                'lat',
                'Required parameter "lat" was null or undefined when calling nearbyCities().'
            );
        }

        if (requestParameters['lon'] == null) {
            throw new runtime.RequiredError(
                'lon',
                'Required parameter "lon" was null or undefined when calling nearbyCities().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lat'] != null) {
            queryParameters['lat'] = requestParameters['lat'];
        }

        if (requestParameters['lon'] != null) {
            queryParameters['lon'] = requestParameters['lon'];
        }

        if (requestParameters['radius'] != null) {
            queryParameters['radius'] = requestParameters['radius'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/cities/nearby`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns cities near a given latitude/longitude within a specified radius. Results are ordered by distance. Uses PostGIS spatial index for fast lookups. 
     * Find nearby cities
     */
    async nearbyCitiesRaw(requestParameters: NearbyCitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NearbyCityListResponse>> {
        const requestOptions = await this.nearbyCitiesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NearbyCityListResponseFromJSON(jsonValue));
    }

    /**
     * Returns cities near a given latitude/longitude within a specified radius. Results are ordered by distance. Uses PostGIS spatial index for fast lookups. 
     * Find nearby cities
     */
    async nearbyCities(requestParameters: NearbyCitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NearbyCityListResponse> {
        const response = await this.nearbyCitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
