/* tslint:disable */
/* eslint-disable */
/**
 * GeoAPI
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CountryListResponse,
  CountrySingleResponse,
  ErrorResponse,
  RegionListResponse,
} from '../models/index';
import {
    CountryListResponseFromJSON,
    CountryListResponseToJSON,
    CountrySingleResponseFromJSON,
    CountrySingleResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    RegionListResponseFromJSON,
    RegionListResponseToJSON,
} from '../models/index';

export interface CountryNeighborsRequest {
    code: string;
    lang?: string;
    fields?: string;
}

export interface GetCountryRequest {
    code: string;
    lang?: string;
    fields?: string;
}

export interface ListCountriesRequest {
    lang?: string;
    continent?: ListCountriesContinentEnum;
    isoCode?: string;
    populationMin?: number;
    populationMax?: number;
    cursor?: string;
    limit?: number;
    fields?: string;
    sort?: string;
}

export interface ListCountryRegionsRequest {
    code: string;
    lang?: string;
    cursor?: string;
    limit?: number;
    fields?: string;
    sort?: string;
}

/**
 * 
 */
export class CountriesApi extends runtime.BaseAPI {

    /**
     * Creates request options for countryNeighbors without sending the request
     */
    async countryNeighborsRequestOpts(requestParameters: CountryNeighborsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling countryNeighbors().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/countries/{code}/neighbors`;
        urlPath = urlPath.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns countries that share a border with the specified country.
     * List neighboring countries
     */
    async countryNeighborsRaw(requestParameters: CountryNeighborsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CountryListResponse>> {
        const requestOptions = await this.countryNeighborsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CountryListResponseFromJSON(jsonValue));
    }

    /**
     * Returns countries that share a border with the specified country.
     * List neighboring countries
     */
    async countryNeighbors(requestParameters: CountryNeighborsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CountryListResponse> {
        const response = await this.countryNeighborsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCountry without sending the request
     */
    async getCountryRequestOpts(requestParameters: GetCountryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling getCountry().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/countries/{code}`;
        urlPath = urlPath.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a single country by its ISO alpha-2 code.
     * Get country by ISO code
     */
    async getCountryRaw(requestParameters: GetCountryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CountrySingleResponse>> {
        const requestOptions = await this.getCountryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CountrySingleResponseFromJSON(jsonValue));
    }

    /**
     * Returns a single country by its ISO alpha-2 code.
     * Get country by ISO code
     */
    async getCountry(requestParameters: GetCountryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CountrySingleResponse> {
        const response = await this.getCountryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCountries without sending the request
     */
    async listCountriesRequestOpts(requestParameters: ListCountriesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['continent'] != null) {
            queryParameters['continent'] = requestParameters['continent'];
        }

        if (requestParameters['isoCode'] != null) {
            queryParameters['iso_code'] = requestParameters['isoCode'];
        }

        if (requestParameters['populationMin'] != null) {
            queryParameters['population_min'] = requestParameters['populationMin'];
        }

        if (requestParameters['populationMax'] != null) {
            queryParameters['population_max'] = requestParameters['populationMax'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/countries`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a paginated list of countries with optional filtering and sorting.
     * List countries
     */
    async listCountriesRaw(requestParameters: ListCountriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CountryListResponse>> {
        const requestOptions = await this.listCountriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CountryListResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of countries with optional filtering and sorting.
     * List countries
     */
    async listCountries(requestParameters: ListCountriesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CountryListResponse> {
        const response = await this.listCountriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCountryRegions without sending the request
     */
    async listCountryRegionsRequestOpts(requestParameters: ListCountryRegionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling listCountryRegions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/countries/{code}/regions`;
        urlPath = urlPath.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a paginated list of regions (administrative divisions) within a country.
     * List regions in a country
     */
    async listCountryRegionsRaw(requestParameters: ListCountryRegionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegionListResponse>> {
        const requestOptions = await this.listCountryRegionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegionListResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of regions (administrative divisions) within a country.
     * List regions in a country
     */
    async listCountryRegions(requestParameters: ListCountryRegionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegionListResponse> {
        const response = await this.listCountryRegionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListCountriesContinentEnum = {
    Af: 'AF',
    An: 'AN',
    As: 'AS',
    Eu: 'EU',
    Na: 'NA',
    Oc: 'OC',
    Sa: 'SA'
} as const;
export type ListCountriesContinentEnum = typeof ListCountriesContinentEnum[keyof typeof ListCountriesContinentEnum];
