/* tslint:disable */
/* eslint-disable */
/**
 * GeoSearch
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  IPSingleResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    IPSingleResponseFromJSON,
    IPSingleResponseToJSON,
} from '../models/index';

export interface LookupIPRequest {
    address: string;
    lang?: string;
    fields?: string;
}

export interface LookupMyIPRequest {
    lang?: string;
    fields?: string;
}

/**
 * 
 */
export class IPGeolocationApi extends runtime.BaseAPI {

    /**
     * Creates request options for lookupIP without sending the request
     */
    async lookupIPRequestOpts(requestParameters: LookupIPRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling lookupIP().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/ip/{address}`;
        urlPath = urlPath.replace(`{${"address"}}`, encodeURIComponent(String(requestParameters['address'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns geolocation data for a given IPv4 or IPv6 address.
     * IP geolocation lookup
     */
    async lookupIPRaw(requestParameters: LookupIPRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IPSingleResponse>> {
        const requestOptions = await this.lookupIPRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IPSingleResponseFromJSON(jsonValue));
    }

    /**
     * Returns geolocation data for a given IPv4 or IPv6 address.
     * IP geolocation lookup
     */
    async lookupIP(requestParameters: LookupIPRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IPSingleResponse> {
        const response = await this.lookupIPRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for lookupMyIP without sending the request
     */
    async lookupMyIPRequestOpts(requestParameters: LookupMyIPRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/ip/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Auto-detects the client\'s IP address (from X-Forwarded-For or RemoteAddr) and returns its geolocation data. 
     * Caller\'s IP geolocation
     */
    async lookupMyIPRaw(requestParameters: LookupMyIPRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IPSingleResponse>> {
        const requestOptions = await this.lookupMyIPRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IPSingleResponseFromJSON(jsonValue));
    }

    /**
     * Auto-detects the client\'s IP address (from X-Forwarded-For or RemoteAddr) and returns its geolocation data. 
     * Caller\'s IP geolocation
     */
    async lookupMyIP(requestParameters: LookupMyIPRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IPSingleResponse> {
        const response = await this.lookupMyIPRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
