/* tslint:disable */
/* eslint-disable */
/**
 * GeoSearch
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CityListResponse,
  ErrorResponse,
  RegionListResponse,
  RegionSingleResponse,
} from '../models/index';
import {
    CityListResponseFromJSON,
    CityListResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    RegionListResponseFromJSON,
    RegionListResponseToJSON,
    RegionSingleResponseFromJSON,
    RegionSingleResponseToJSON,
} from '../models/index';

export interface GetRegionRequest {
    id: number;
    lang?: string;
    fields?: string;
}

export interface ListRegionCitiesRequest {
    id: number;
    lang?: string;
    cursor?: string;
    limit?: number;
    fields?: string;
    sort?: string;
}

export interface ListRegionsRequest {
    lang?: string;
    country?: string;
    level?: number;
    populationMin?: number;
    populationMax?: number;
    cursor?: string;
    limit?: number;
    fields?: string;
    sort?: string;
}

export interface RegionChildrenRequest {
    id: number;
    lang?: string;
    fields?: string;
}

/**
 * 
 */
export class RegionsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getRegion without sending the request
     */
    async getRegionRequestOpts(requestParameters: GetRegionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRegion().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/regions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a single region by its numeric ID.
     * Get region by ID
     */
    async getRegionRaw(requestParameters: GetRegionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegionSingleResponse>> {
        const requestOptions = await this.getRegionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegionSingleResponseFromJSON(jsonValue));
    }

    /**
     * Returns a single region by its numeric ID.
     * Get region by ID
     */
    async getRegion(requestParameters: GetRegionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegionSingleResponse> {
        const response = await this.getRegionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listRegionCities without sending the request
     */
    async listRegionCitiesRequestOpts(requestParameters: ListRegionCitiesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listRegionCities().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/regions/{id}/cities`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a paginated list of cities within a specific region.  THIS ENDPOINT AND `/v1/cities?within=` ANSWER DIFFERENT QUESTIONS AND WILL SOMETIMES RETURN DIFFERENT CITIES FOR THE SAME REGION. That is intended, not a bug. This endpoint answers the ADMINISTRATIVE question — which cities are assigned to this region by GeoNames\' own admin codes — while `?within=` answers the GEOMETRIC one, which cities fall inside the region\'s polygon. The two disagree wherever an enclave, an exclave or a blank admin code puts a city\'s assignment at odds with its location.  Use this endpoint when you want the official assignment; use `/v1/cities?within=` when you want what is physically inside the boundary. This one is charged at the standard 1 unit; `?within=` costs 2.
     * List cities in a region
     */
    async listRegionCitiesRaw(requestParameters: ListRegionCitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CityListResponse>> {
        const requestOptions = await this.listRegionCitiesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CityListResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of cities within a specific region.  THIS ENDPOINT AND `/v1/cities?within=` ANSWER DIFFERENT QUESTIONS AND WILL SOMETIMES RETURN DIFFERENT CITIES FOR THE SAME REGION. That is intended, not a bug. This endpoint answers the ADMINISTRATIVE question — which cities are assigned to this region by GeoNames\' own admin codes — while `?within=` answers the GEOMETRIC one, which cities fall inside the region\'s polygon. The two disagree wherever an enclave, an exclave or a blank admin code puts a city\'s assignment at odds with its location.  Use this endpoint when you want the official assignment; use `/v1/cities?within=` when you want what is physically inside the boundary. This one is charged at the standard 1 unit; `?within=` costs 2.
     * List cities in a region
     */
    async listRegionCities(requestParameters: ListRegionCitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CityListResponse> {
        const response = await this.listRegionCitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listRegions without sending the request
     */
    async listRegionsRequestOpts(requestParameters: ListRegionsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['country'] != null) {
            queryParameters['country'] = requestParameters['country'];
        }

        if (requestParameters['level'] != null) {
            queryParameters['level'] = requestParameters['level'];
        }

        if (requestParameters['populationMin'] != null) {
            queryParameters['population_min'] = requestParameters['populationMin'];
        }

        if (requestParameters['populationMax'] != null) {
            queryParameters['population_max'] = requestParameters['populationMax'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/regions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a paginated list of regions with optional filtering by country, level, and population.
     * List regions
     */
    async listRegionsRaw(requestParameters: ListRegionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegionListResponse>> {
        const requestOptions = await this.listRegionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegionListResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of regions with optional filtering by country, level, and population.
     * List regions
     */
    async listRegions(requestParameters: ListRegionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegionListResponse> {
        const response = await this.listRegionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for regionChildren without sending the request
     */
    async regionChildrenRequestOpts(requestParameters: RegionChildrenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling regionChildren().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/regions/{id}/children`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all cities that are direct children of the specified region in the administrative hierarchy.
     * List child cities of a region
     */
    async regionChildrenRaw(requestParameters: RegionChildrenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CityListResponse>> {
        const requestOptions = await this.regionChildrenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CityListResponseFromJSON(jsonValue));
    }

    /**
     * Returns all cities that are direct children of the specified region in the administrative hierarchy.
     * List child cities of a region
     */
    async regionChildren(requestParameters: RegionChildrenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CityListResponse> {
        const response = await this.regionChildrenRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
