/* tslint:disable */
/* eslint-disable */
/**
 * GeoAPI
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AutocompleteListResponse,
  ErrorResponse,
  HierarchyListResponse,
  ReverseGeocodeSingleResponse,
  SearchListResponse,
} from '../models/index';
import {
    AutocompleteListResponseFromJSON,
    AutocompleteListResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HierarchyListResponseFromJSON,
    HierarchyListResponseToJSON,
    ReverseGeocodeSingleResponseFromJSON,
    ReverseGeocodeSingleResponseToJSON,
    SearchListResponseFromJSON,
    SearchListResponseToJSON,
} from '../models/index';

export interface AutocompleteRequest {
    q: string;
    lang?: string;
    limit?: number;
    fields?: string;
}

export interface ResolveCoordinateRequest {
    lat: number;
    lon: number;
    lang?: string;
}

export interface ReverseGeocodeRequest {
    lat: number;
    lon: number;
    fields?: string;
}

export interface SearchRequest {
    q: string;
    lang?: string;
    type?: string;
    limit?: number;
    fields?: string;
}

/**
 * 
 */
export class SearchApi extends runtime.BaseAPI {

    /**
     * Creates request options for autocomplete without sending the request
     */
    async autocompleteRequestOpts(requestParameters: AutocompleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling autocomplete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/autocomplete`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns autocomplete suggestions matching a query string across cities, regions, and countries. Results are ranked by relevance and population. Minimum 2 characters required. 
     * Autocomplete search
     */
    async autocompleteRaw(requestParameters: AutocompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AutocompleteListResponse>> {
        const requestOptions = await this.autocompleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AutocompleteListResponseFromJSON(jsonValue));
    }

    /**
     * Returns autocomplete suggestions matching a query string across cities, regions, and countries. Results are ranked by relevance and population. Minimum 2 characters required. 
     * Autocomplete search
     */
    async autocomplete(requestParameters: AutocompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AutocompleteListResponse> {
        const response = await this.autocompleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resolveCoordinate without sending the request
     */
    async resolveCoordinateRequestOpts(requestParameters: ResolveCoordinateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['lat'] == null) {
            throw new runtime.RequiredError(
                'lat',
                'Required parameter "lat" was null or undefined when calling resolveCoordinate().'
            );
        }

        if (requestParameters['lon'] == null) {
            throw new runtime.RequiredError(
                'lon',
                'Required parameter "lon" was null or undefined when calling resolveCoordinate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lat'] != null) {
            queryParameters['lat'] = requestParameters['lat'];
        }

        if (requestParameters['lon'] != null) {
            queryParameters['lon'] = requestParameters['lon'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/resolve`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the administrative areas whose BOUNDARY POLYGONS CONTAIN the given coordinate, ordered country first.  ## How this differs from `/v1/reverse`  These two endpoints take the same parameters and answer different questions, and the difference is the reason both exist.  `/v1/reverse` returns the NEAREST city. It always returns something, and for a point near a border that something is sometimes in the neighbouring country.  `/v1/resolve` returns the areas that actually CONTAIN the point. It is never wrong about which country a point is in — and it sometimes returns nothing at all, because no polygon covers the point or because we hold no polygon for that country. Choose this endpoint when correctness at borders matters and choose `/v1/reverse` when you always need an answer.  ## `depth` RUNS THE OPPOSITE DIRECTION FROM `/v1/cities/{id}/hierarchy`  Read this before writing code that consumes both endpoints.  Both return the same node SHAPE — `geoname_id`, `name`, `type`, `depth` — so one rendering path can accept either. The `depth` SEMANTICS are inverted between them:  - On **this** endpoint `depth` is POSITIONAL, counting outward-in from   the largest area: **`depth: 0` is the COUNTRY**, `depth: 1` is the   region inside it, and so on. - On **`/v1/cities/{id}/hierarchy`** `depth` counts up from the entity   that was asked about: `depth: 0` is the CITY, and the country is at the   highest depth in the list.  So `data[0]` is the country here and the city there. Code that sorts or indexes on `depth` across both endpoints without accounting for this will silently invert the hierarchy rather than fail.  ## Cost and availability  One quota unit, on every plan including Free. This is a single indexed point-in-polygon probe returning names, not a geometry transfer, so it carries no premium and no tier gate.  `?fields=` IS NOT SUPPORTED on this endpoint and is ignored if sent. The four node fields are all small, so selection would save nothing. 
     * Resolve coordinates to their containing administrative areas
     */
    async resolveCoordinateRaw(requestParameters: ResolveCoordinateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HierarchyListResponse>> {
        const requestOptions = await this.resolveCoordinateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HierarchyListResponseFromJSON(jsonValue));
    }

    /**
     * Returns the administrative areas whose BOUNDARY POLYGONS CONTAIN the given coordinate, ordered country first.  ## How this differs from `/v1/reverse`  These two endpoints take the same parameters and answer different questions, and the difference is the reason both exist.  `/v1/reverse` returns the NEAREST city. It always returns something, and for a point near a border that something is sometimes in the neighbouring country.  `/v1/resolve` returns the areas that actually CONTAIN the point. It is never wrong about which country a point is in — and it sometimes returns nothing at all, because no polygon covers the point or because we hold no polygon for that country. Choose this endpoint when correctness at borders matters and choose `/v1/reverse` when you always need an answer.  ## `depth` RUNS THE OPPOSITE DIRECTION FROM `/v1/cities/{id}/hierarchy`  Read this before writing code that consumes both endpoints.  Both return the same node SHAPE — `geoname_id`, `name`, `type`, `depth` — so one rendering path can accept either. The `depth` SEMANTICS are inverted between them:  - On **this** endpoint `depth` is POSITIONAL, counting outward-in from   the largest area: **`depth: 0` is the COUNTRY**, `depth: 1` is the   region inside it, and so on. - On **`/v1/cities/{id}/hierarchy`** `depth` counts up from the entity   that was asked about: `depth: 0` is the CITY, and the country is at the   highest depth in the list.  So `data[0]` is the country here and the city there. Code that sorts or indexes on `depth` across both endpoints without accounting for this will silently invert the hierarchy rather than fail.  ## Cost and availability  One quota unit, on every plan including Free. This is a single indexed point-in-polygon probe returning names, not a geometry transfer, so it carries no premium and no tier gate.  `?fields=` IS NOT SUPPORTED on this endpoint and is ignored if sent. The four node fields are all small, so selection would save nothing. 
     * Resolve coordinates to their containing administrative areas
     */
    async resolveCoordinate(requestParameters: ResolveCoordinateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HierarchyListResponse> {
        const response = await this.resolveCoordinateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for reverseGeocode without sending the request
     */
    async reverseGeocodeRequestOpts(requestParameters: ReverseGeocodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['lat'] == null) {
            throw new runtime.RequiredError(
                'lat',
                'Required parameter "lat" was null or undefined when calling reverseGeocode().'
            );
        }

        if (requestParameters['lon'] == null) {
            throw new runtime.RequiredError(
                'lon',
                'Required parameter "lon" was null or undefined when calling reverseGeocode().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lat'] != null) {
            queryParameters['lat'] = requestParameters['lat'];
        }

        if (requestParameters['lon'] != null) {
            queryParameters['lon'] = requestParameters['lon'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/reverse`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the nearest city for a given latitude/longitude. Uses PostGIS spatial index for fast reverse geocoding. 
     * Reverse geocode coordinates
     */
    async reverseGeocodeRaw(requestParameters: ReverseGeocodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReverseGeocodeSingleResponse>> {
        const requestOptions = await this.reverseGeocodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReverseGeocodeSingleResponseFromJSON(jsonValue));
    }

    /**
     * Returns the nearest city for a given latitude/longitude. Uses PostGIS spatial index for fast reverse geocoding. 
     * Reverse geocode coordinates
     */
    async reverseGeocode(requestParameters: ReverseGeocodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReverseGeocodeSingleResponse> {
        const response = await this.reverseGeocodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for search without sending the request
     */
    async searchRequestOpts(requestParameters: SearchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling search().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/search`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Performs a fuzzy text search across countries, regions, and cities using trigram matching. Results are ranked by relevance and population. Uses simple limit pagination (no cursor). 
     * Cross-type search
     */
    async searchRaw(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchListResponse>> {
        const requestOptions = await this.searchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchListResponseFromJSON(jsonValue));
    }

    /**
     * Performs a fuzzy text search across countries, regions, and cities using trigram matching. Results are ranked by relevance and population. Uses simple limit pagination (no cursor). 
     * Cross-type search
     */
    async search(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchListResponse> {
        const response = await this.searchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
