/* tslint:disable */
/* eslint-disable */
/**
 * GeoSearch
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.3.2
 * Contact: info@geosearch.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  TimezoneListResponse,
  TimezoneSingleResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    TimezoneListResponseFromJSON,
    TimezoneListResponseToJSON,
    TimezoneSingleResponseFromJSON,
    TimezoneSingleResponseToJSON,
} from '../models/index';

export interface GetTimezoneRequest {
    tzId: string;
    lang?: string;
    fields?: string;
}

export interface ListTimezonesRequest {
    lang?: string;
    country?: string;
    cursor?: string;
    limit?: number;
    fields?: string;
    sort?: string;
}

/**
 * 
 */
export class TimezonesApi extends runtime.BaseAPI {

    /**
     * Creates request options for getTimezone without sending the request
     */
    async getTimezoneRequestOpts(requestParameters: GetTimezoneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tzId'] == null) {
            throw new runtime.RequiredError(
                'tzId',
                'Required parameter "tzId" was null or undefined when calling getTimezone().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/timezones/{tzId}`;
        urlPath = urlPath.replace(`{${"tzId"}}`, encodeURIComponent(String(requestParameters['tzId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a single timezone by its IANA identifier. Note: IANA timezone IDs contain slashes (e.g., America/New_York), so the path uses a wildcard match. 
     * Get timezone by IANA ID
     */
    async getTimezoneRaw(requestParameters: GetTimezoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimezoneSingleResponse>> {
        const requestOptions = await this.getTimezoneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimezoneSingleResponseFromJSON(jsonValue));
    }

    /**
     * Returns a single timezone by its IANA identifier. Note: IANA timezone IDs contain slashes (e.g., America/New_York), so the path uses a wildcard match. 
     * Get timezone by IANA ID
     */
    async getTimezone(requestParameters: GetTimezoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimezoneSingleResponse> {
        const response = await this.getTimezoneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTimezones without sending the request
     */
    async listTimezonesRequestOpts(requestParameters: ListTimezonesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['country'] != null) {
            queryParameters['country'] = requestParameters['country'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }


        let urlPath = `/v1/timezones`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a paginated list of timezones with optional filtering by country.
     * List timezones
     */
    async listTimezonesRaw(requestParameters: ListTimezonesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimezoneListResponse>> {
        const requestOptions = await this.listTimezonesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimezoneListResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of timezones with optional filtering by country.
     * List timezones
     */
    async listTimezones(requestParameters: ListTimezonesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimezoneListResponse> {
        const response = await this.listTimezonesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
