/* tslint:disable */
/* eslint-disable */
/**
 * GeoAPI
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutocompleteResult
 */
export interface AutocompleteResult {
    /**
     * 
     * @type {number}
     * @memberof AutocompleteResult
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AutocompleteResult
     */
    name?: string;
    /**
     * 
     * @type {AutocompleteResultTypeEnum}
     * @memberof AutocompleteResult
     */
    type?: AutocompleteResultTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AutocompleteResult
     */
    countryCode?: string;
    /**
     * 
     * @type {number}
     * @memberof AutocompleteResult
     */
    population?: number;
}


/**
 * @export
 */
export const AutocompleteResultTypeEnum = {
    Country: 'country',
    Region: 'region',
    City: 'city'
} as const;
export type AutocompleteResultTypeEnum = typeof AutocompleteResultTypeEnum[keyof typeof AutocompleteResultTypeEnum];


/**
 * Check if a given object implements the AutocompleteResult interface.
 */
export function instanceOfAutocompleteResult(value: object): value is AutocompleteResult {
    return true;
}

export function AutocompleteResultFromJSON(json: any): AutocompleteResult {
    return AutocompleteResultFromJSONTyped(json, false);
}

export function AutocompleteResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'countryCode': json['country_code'] == null ? undefined : json['country_code'],
        'population': json['population'] == null ? undefined : json['population'],
    };
}

export function AutocompleteResultToJSON(json: any): AutocompleteResult {
    return AutocompleteResultToJSONTyped(json, false);
}

export function AutocompleteResultToJSONTyped(value?: AutocompleteResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
        'country_code': value['countryCode'],
        'population': value['population'],
    };
}

