/* tslint:disable */
/* eslint-disable */
/**
 * GeoSearch
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.3.2
 * Contact: info@geosearch.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoJSONGeometry } from './GeoJSONGeometry';
import {
    GeoJSONGeometryFromJSON,
    GeoJSONGeometryFromJSONTyped,
    GeoJSONGeometryToJSON,
    GeoJSONGeometryToJSONTyped,
} from './GeoJSONGeometry';

/**
 * One area's boundary polygon, as returned by `GET /v1/boundaries/{geoname_id}`.
 * @export
 * @interface Boundary
 */
export interface Boundary {
    /**
     * The area the polygon belongs to, read back from the source row rather than echoed from the request.
     * @type {number}
     * @memberof Boundary
     */
    geonameId: number;
    /**
     * The area's name, resolved through `?lang=` when supplied.
     * @type {string}
     * @memberof Boundary
     */
    name: string;
    /**
     * Which kind of area this is.
     * @type {BoundaryTypeEnum}
     * @memberof Boundary
     */
    type: BoundaryTypeEnum;
    /**
     * 
     * @type {GeoJSONGeometry}
     * @memberof Boundary
     */
    geometry: GeoJSONGeometry;
    /**
     * The tolerance that was ACTUALLY APPLIED, or `null` for full precision.
     * 
     * THIS IS NOT YOUR `?simplify=` ECHOED BACK. A requested tolerance of `0` is dropped rather than executed, so `?simplify=0` returns `null` here — that is the truthful answer, because no simplification was performed. Read this field rather than assuming the request was honoured verbatim.
     * @type {number}
     * @memberof Boundary
     */
    simplify: number;
}


/**
 * @export
 */
export const BoundaryTypeEnum = {
    Country: 'country',
    Region: 'region'
} as const;
export type BoundaryTypeEnum = typeof BoundaryTypeEnum[keyof typeof BoundaryTypeEnum];


/**
 * Check if a given object implements the Boundary interface.
 */
export function instanceOfBoundary(value: object): value is Boundary {
    if (!('geonameId' in value) || value['geonameId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('geometry' in value) || value['geometry'] === undefined) return false;
    if (!('simplify' in value) || value['simplify'] === undefined) return false;
    return true;
}

export function BoundaryFromJSON(json: any): Boundary {
    return BoundaryFromJSONTyped(json, false);
}

export function BoundaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Boundary {
    if (json == null) {
        return json;
    }
    return {
        
        'geonameId': json['geoname_id'],
        'name': json['name'],
        'type': json['type'],
        'geometry': GeoJSONGeometryFromJSON(json['geometry']),
        'simplify': json['simplify'],
    };
}

export function BoundaryToJSON(json: any): Boundary {
    return BoundaryToJSONTyped(json, false);
}

export function BoundaryToJSONTyped(value?: Boundary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'geoname_id': value['geonameId'],
        'name': value['name'],
        'type': value['type'],
        'geometry': GeoJSONGeometryToJSON(value['geometry']),
        'simplify': value['simplify'],
    };
}

