/* tslint:disable */
/* eslint-disable */
/**
 * GeoSearch
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, and timezones through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: info@geosearch.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CountryRef } from './CountryRef.js';
import {
    CountryRefFromJSON,
    CountryRefFromJSONTyped,
    CountryRefToJSON,
    CountryRefToJSONTyped,
} from './CountryRef.js';
import type { RegionRef } from './RegionRef.js';
import {
    RegionRefFromJSON,
    RegionRefFromJSONTyped,
    RegionRefToJSON,
    RegionRefToJSONTyped,
} from './RegionRef.js';

/**
 * 
 * @export
 * @interface City
 */
export interface City {
    /**
     * 
     * @type {number}
     * @memberof City
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof City
     */
    geonameId?: number;
    /**
     * 
     * @type {string}
     * @memberof City
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof City
     */
    asciiName?: string;
    /**
     * 
     * @type {string}
     * @memberof City
     */
    countryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof City
     */
    admin1Code?: string;
    /**
     * 
     * @type {string}
     * @memberof City
     */
    admin2Code?: string;
    /**
     * 
     * @type {number}
     * @memberof City
     */
    population?: number;
    /**
     * 
     * @type {number}
     * @memberof City
     */
    elevation?: number;
    /**
     * 
     * @type {string}
     * @memberof City
     */
    timezone?: string;
    /**
     * 
     * @type {number}
     * @memberof City
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof City
     */
    longitude?: number;
    /**
     * 
     * @type {CountryRef}
     * @memberof City
     */
    country?: CountryRef;
    /**
     * 
     * @type {RegionRef}
     * @memberof City
     */
    region?: RegionRef;
}

/**
 * Check if a given object implements the City interface.
 */
export function instanceOfCity(value: object): value is City {
    return true;
}

export function CityFromJSON(json: any): City {
    return CityFromJSONTyped(json, false);
}

export function CityFromJSONTyped(json: any, ignoreDiscriminator: boolean): City {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'geonameId': json['geoname_id'] == null ? undefined : json['geoname_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'asciiName': json['ascii_name'] == null ? undefined : json['ascii_name'],
        'countryCode': json['country_code'] == null ? undefined : json['country_code'],
        'admin1Code': json['admin1_code'] == null ? undefined : json['admin1_code'],
        'admin2Code': json['admin2_code'] == null ? undefined : json['admin2_code'],
        'population': json['population'] == null ? undefined : json['population'],
        'elevation': json['elevation'] == null ? undefined : json['elevation'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'country': json['country'] == null ? undefined : CountryRefFromJSON(json['country']),
        'region': json['region'] == null ? undefined : RegionRefFromJSON(json['region']),
    };
}

export function CityToJSON(json: any): City {
    return CityToJSONTyped(json, false);
}

export function CityToJSONTyped(value?: City | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'geoname_id': value['geonameId'],
        'name': value['name'],
        'ascii_name': value['asciiName'],
        'country_code': value['countryCode'],
        'admin1_code': value['admin1Code'],
        'admin2_code': value['admin2Code'],
        'population': value['population'],
        'elevation': value['elevation'],
        'timezone': value['timezone'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'country': CountryRefToJSON(value['country']),
        'region': RegionRefToJSON(value['region']),
    };
}

