/* tslint:disable */
/* eslint-disable */
/**
 * GeoAPI
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoJSONMultiPolygon } from './GeoJSONMultiPolygon';
import {
    GeoJSONMultiPolygonFromJSON,
    GeoJSONMultiPolygonFromJSONTyped,
    GeoJSONMultiPolygonToJSON,
    GeoJSONMultiPolygonToJSONTyped,
} from './GeoJSONMultiPolygon';

/**
 * 
 * @export
 * @interface Country
 */
export interface Country {
    /**
     * 
     * @type {number}
     * @memberof Country
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Country
     */
    geonameId?: number;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    isoCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    iso3Code?: string;
    /**
     * 
     * @type {number}
     * @memberof Country
     */
    isoNumeric?: number;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    fipsCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    capital?: string;
    /**
     * 
     * @type {number}
     * @memberof Country
     */
    areaSqKm?: number;
    /**
     * 
     * @type {number}
     * @memberof Country
     */
    population?: number;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    continentCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    tld?: string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    currencyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    currencyName?: string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    postalCodeFormat?: string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    postalCodeRegex?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Country
     */
    languages?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Country
     */
    neighbours?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof Country
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof Country
     */
    longitude?: number;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    flagEmoji?: string;
    /**
     * Country boundary. Returned by default on `GET /v1/countries/{code}` and on request via `?fields=geometry` on `GET /v1/countries`.
     * 
     * NOT TIER-GATED. Country geometry is served on every plan, including Free. Region geometry is gated — see the `Region` schema.
     * @type {GeoJSONMultiPolygon}
     * @memberof Country
     */
    geometry?: GeoJSONMultiPolygon;
}

/**
 * Check if a given object implements the Country interface.
 */
export function instanceOfCountry(value: object): value is Country {
    return true;
}

export function CountryFromJSON(json: any): Country {
    return CountryFromJSONTyped(json, false);
}

export function CountryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Country {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'geonameId': json['geoname_id'] == null ? undefined : json['geoname_id'],
        'isoCode': json['iso_code'] == null ? undefined : json['iso_code'],
        'iso3Code': json['iso3_code'] == null ? undefined : json['iso3_code'],
        'isoNumeric': json['iso_numeric'] == null ? undefined : json['iso_numeric'],
        'fipsCode': json['fips_code'] == null ? undefined : json['fips_code'],
        'name': json['name'] == null ? undefined : json['name'],
        'capital': json['capital'] == null ? undefined : json['capital'],
        'areaSqKm': json['area_sq_km'] == null ? undefined : json['area_sq_km'],
        'population': json['population'] == null ? undefined : json['population'],
        'continentCode': json['continent_code'] == null ? undefined : json['continent_code'],
        'tld': json['tld'] == null ? undefined : json['tld'],
        'currencyCode': json['currency_code'] == null ? undefined : json['currency_code'],
        'currencyName': json['currency_name'] == null ? undefined : json['currency_name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'postalCodeFormat': json['postal_code_format'] == null ? undefined : json['postal_code_format'],
        'postalCodeRegex': json['postal_code_regex'] == null ? undefined : json['postal_code_regex'],
        'languages': json['languages'] == null ? undefined : json['languages'],
        'neighbours': json['neighbours'] == null ? undefined : json['neighbours'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'flagEmoji': json['flag_emoji'] == null ? undefined : json['flag_emoji'],
        'geometry': json['geometry'] == null ? undefined : GeoJSONMultiPolygonFromJSON(json['geometry']),
    };
}

export function CountryToJSON(json: any): Country {
    return CountryToJSONTyped(json, false);
}

export function CountryToJSONTyped(value?: Country | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'geoname_id': value['geonameId'],
        'iso_code': value['isoCode'],
        'iso3_code': value['iso3Code'],
        'iso_numeric': value['isoNumeric'],
        'fips_code': value['fipsCode'],
        'name': value['name'],
        'capital': value['capital'],
        'area_sq_km': value['areaSqKm'],
        'population': value['population'],
        'continent_code': value['continentCode'],
        'tld': value['tld'],
        'currency_code': value['currencyCode'],
        'currency_name': value['currencyName'],
        'phone': value['phone'],
        'postal_code_format': value['postalCodeFormat'],
        'postal_code_regex': value['postalCodeRegex'],
        'languages': value['languages'],
        'neighbours': value['neighbours'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'flag_emoji': value['flagEmoji'],
        'geometry': GeoJSONMultiPolygonToJSON(value['geometry']),
    };
}

