/* tslint:disable */
/* eslint-disable */
/**
 * GeoSearch
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.3.2
 * Contact: info@geosearch.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuotaDetail } from './QuotaDetail';
import {
    QuotaDetailFromJSON,
    QuotaDetailFromJSONTyped,
    QuotaDetailToJSON,
    QuotaDetailToJSONTyped,
} from './QuotaDetail';
import type { UpgradeDetail } from './UpgradeDetail';
import {
    UpgradeDetailFromJSON,
    UpgradeDetailFromJSONTyped,
    UpgradeDetailToJSON,
    UpgradeDetailToJSONTyped,
} from './UpgradeDetail';
import type { ErrorResponseErrorDetailsInner } from './ErrorResponseErrorDetailsInner';
import {
    ErrorResponseErrorDetailsInnerFromJSON,
    ErrorResponseErrorDetailsInnerFromJSONTyped,
    ErrorResponseErrorDetailsInnerToJSON,
    ErrorResponseErrorDetailsInnerToJSONTyped,
} from './ErrorResponseErrorDetailsInner';

/**
 * 
 * @export
 * @interface ErrorResponseError
 */
export interface ErrorResponseError {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseError
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseError
     */
    message: string;
    /**
     * 
     * @type {Array<ErrorResponseErrorDetailsInner>}
     * @memberof ErrorResponseError
     */
    details?: Array<ErrorResponseErrorDetailsInner>;
    /**
     * Correlation identifier present on every error response. Quote this when contacting support.
     * @type {string}
     * @memberof ErrorResponseError
     */
    requestId: string;
    /**
     * W3C trace ID of the distributed trace for this request, when tracing is enabled. Omitted entirely when no span was recording, so clients must treat it as optional. It complements rather than replaces `request_id`.
     * @type {string}
     * @memberof ErrorResponseError
     */
    traceId?: string;
    /**
     * 
     * @type {QuotaDetail}
     * @memberof ErrorResponseError
     */
    quota?: QuotaDetail;
    /**
     * 
     * @type {UpgradeDetail}
     * @memberof ErrorResponseError
     */
    upgrade?: UpgradeDetail;
}

/**
 * Check if a given object implements the ErrorResponseError interface.
 */
export function instanceOfErrorResponseError(value: object): value is ErrorResponseError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function ErrorResponseErrorFromJSON(json: any): ErrorResponseError {
    return ErrorResponseErrorFromJSONTyped(json, false);
}

export function ErrorResponseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
        'details': json['details'] == null ? undefined : ((json['details'] as Array<any>).map(ErrorResponseErrorDetailsInnerFromJSON)),
        'requestId': json['request_id'],
        'traceId': json['trace_id'] == null ? undefined : json['trace_id'],
        'quota': json['quota'] == null ? undefined : QuotaDetailFromJSON(json['quota']),
        'upgrade': json['upgrade'] == null ? undefined : UpgradeDetailFromJSON(json['upgrade']),
    };
}

export function ErrorResponseErrorToJSON(json: any): ErrorResponseError {
    return ErrorResponseErrorToJSONTyped(json, false);
}

export function ErrorResponseErrorToJSONTyped(value?: ErrorResponseError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'details': value['details'] == null ? undefined : ((value['details'] as Array<any>).map(ErrorResponseErrorDetailsInnerToJSON)),
        'request_id': value['requestId'],
        'trace_id': value['traceId'],
        'quota': QuotaDetailToJSON(value['quota']),
        'upgrade': UpgradeDetailToJSON(value['upgrade']),
    };
}

