/* tslint:disable */
/* eslint-disable */
/**
 * GeoSearch
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * GeoJSON MultiPolygon geometry.
 * 
 * WHEN IT IS RETURNED DEPENDS ON THE ENDPOINT AND ON THE PLAN, and there is no single rule. The previous wording here — "only returned when explicitly requested via `?fields=geometry`" — was false in both directions and is corrected below.
 * 
 * `GET /v1/countries/{code}` and `GET /v1/regions/{id}`: returned by default. These are detail endpoints and they have always served geometry without `?fields=geometry` being present.
 * 
 * `GET /v1/countries`, `GET /v1/regions` and `GET /v1/countries/{code}/regions`: returned only when `?fields=geometry` is requested. Omitting it from a list response is a payload decision — a 100-row page of region polygons is several megabytes.
 * 
 * REGION GEOMETRY ADDITIONALLY REQUIRES A PAID PLAN. On `GET /v1/regions/{id}`, `GET /v1/regions?fields=geometry` and `GET /v1/countries/{code}/regions?fields=geometry`, the `geometry` key is OMITTED ENTIRELY for Free-tier keys — absent, not null. Country geometry is not gated: `GET /v1/countries/{code}` and `GET /v1/countries?fields=geometry` serve it on every plan, including Free.
 * 
 * The omission is silent by design: it is not an error, and these endpoints still return 200. A client that reads `data.geometry.type` without checking for the key will fail on a null dereference rather than receive a typed zero. To fetch a boundary polygon explicitly — and to receive a 403 with an upgrade link rather than a silent omission when the plan does not include it — use `GET /v1/boundaries/{geoname_id}`.
 * @export
 * @interface GeoJSONMultiPolygon
 */
export interface GeoJSONMultiPolygon {
    /**
     * 
     * @type {GeoJSONMultiPolygonTypeEnum}
     * @memberof GeoJSONMultiPolygon
     */
    type?: GeoJSONMultiPolygonTypeEnum;
    /**
     * 
     * @type {Array<Array<Array<Array<number>>>>}
     * @memberof GeoJSONMultiPolygon
     */
    coordinates?: Array<Array<Array<Array<number>>>>;
}


/**
 * @export
 */
export const GeoJSONMultiPolygonTypeEnum = {
    MultiPolygon: 'MultiPolygon'
} as const;
export type GeoJSONMultiPolygonTypeEnum = typeof GeoJSONMultiPolygonTypeEnum[keyof typeof GeoJSONMultiPolygonTypeEnum];


/**
 * Check if a given object implements the GeoJSONMultiPolygon interface.
 */
export function instanceOfGeoJSONMultiPolygon(value: object): value is GeoJSONMultiPolygon {
    return true;
}

export function GeoJSONMultiPolygonFromJSON(json: any): GeoJSONMultiPolygon {
    return GeoJSONMultiPolygonFromJSONTyped(json, false);
}

export function GeoJSONMultiPolygonFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoJSONMultiPolygon {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'coordinates': json['coordinates'] == null ? undefined : json['coordinates'],
    };
}

export function GeoJSONMultiPolygonToJSON(json: any): GeoJSONMultiPolygon {
    return GeoJSONMultiPolygonToJSONTyped(json, false);
}

export function GeoJSONMultiPolygonToJSONTyped(value?: GeoJSONMultiPolygon | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'coordinates': value['coordinates'],
    };
}

