/* tslint:disable */
/* eslint-disable */
/**
 * GeoSearch
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A bare GeoJSON geometry — the `{"type": ..., "coordinates": ...}` object itself, NOT a GeoJSON `Feature`. There is no `properties` wrapper.
 * @export
 * @interface GeoJSONGeometry
 */
export interface GeoJSONGeometry {
    /**
     * `MultiPolygon` for most areas, `Polygon` for areas with a single ring — including areas that BECOME single-ring under `?simplify=`. Do not pin this to one value.
     * @type {GeoJSONGeometryTypeEnum}
     * @memberof GeoJSONGeometry
     */
    type: GeoJSONGeometryTypeEnum;
    /**
     * Nesting depth depends on `type`: three levels for `Polygon`, four for `MultiPolygon`. Positions are `[longitude, latitude]` in EPSG:4326, per the GeoJSON specification.
     * @type {Array<any>}
     * @memberof GeoJSONGeometry
     */
    coordinates: Array<any>;
}


/**
 * @export
 */
export const GeoJSONGeometryTypeEnum = {
    Polygon: 'Polygon',
    MultiPolygon: 'MultiPolygon'
} as const;
export type GeoJSONGeometryTypeEnum = typeof GeoJSONGeometryTypeEnum[keyof typeof GeoJSONGeometryTypeEnum];


/**
 * Check if a given object implements the GeoJSONGeometry interface.
 */
export function instanceOfGeoJSONGeometry(value: object): value is GeoJSONGeometry {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    return true;
}

export function GeoJSONGeometryFromJSON(json: any): GeoJSONGeometry {
    return GeoJSONGeometryFromJSONTyped(json, false);
}

export function GeoJSONGeometryFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoJSONGeometry {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'coordinates': json['coordinates'],
    };
}

export function GeoJSONGeometryToJSON(json: any): GeoJSONGeometry {
    return GeoJSONGeometryToJSONTyped(json, false);
}

export function GeoJSONGeometryToJSONTyped(value?: GeoJSONGeometry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'coordinates': value['coordinates'],
    };
}

