/* tslint:disable */
/* eslint-disable */
/**
 * GeoSearch
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetStatus200ResponseData
 */
export interface GetStatus200ResponseData {
    /**
     * 
     * @type {GetStatus200ResponseDataStatusEnum}
     * @memberof GetStatus200ResponseData
     */
    status?: GetStatus200ResponseDataStatusEnum;
    /**
     * 
     * @type {GetStatus200ResponseDataDatabaseEnum}
     * @memberof GetStatus200ResponseData
     */
    database?: GetStatus200ResponseDataDatabaseEnum;
}


/**
 * @export
 */
export const GetStatus200ResponseDataStatusEnum = {
    Healthy: 'healthy',
    Degraded: 'degraded'
} as const;
export type GetStatus200ResponseDataStatusEnum = typeof GetStatus200ResponseDataStatusEnum[keyof typeof GetStatus200ResponseDataStatusEnum];

/**
 * @export
 */
export const GetStatus200ResponseDataDatabaseEnum = {
    Connected: 'connected',
    Disconnected: 'disconnected'
} as const;
export type GetStatus200ResponseDataDatabaseEnum = typeof GetStatus200ResponseDataDatabaseEnum[keyof typeof GetStatus200ResponseDataDatabaseEnum];


/**
 * Check if a given object implements the GetStatus200ResponseData interface.
 */
export function instanceOfGetStatus200ResponseData(value: object): value is GetStatus200ResponseData {
    return true;
}

export function GetStatus200ResponseDataFromJSON(json: any): GetStatus200ResponseData {
    return GetStatus200ResponseDataFromJSONTyped(json, false);
}

export function GetStatus200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatus200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'database': json['database'] == null ? undefined : json['database'],
    };
}

export function GetStatus200ResponseDataToJSON(json: any): GetStatus200ResponseData {
    return GetStatus200ResponseDataToJSONTyped(json, false);
}

export function GetStatus200ResponseDataToJSONTyped(value?: GetStatus200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'database': value['database'],
    };
}

