/* tslint:disable */
/* eslint-disable */
/**
 * GeoAPI
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { HierarchyNode } from './HierarchyNode';
import {
    HierarchyNodeFromJSON,
    HierarchyNodeFromJSONTyped,
    HierarchyNodeToJSON,
    HierarchyNodeToJSONTyped,
} from './HierarchyNode';

/**
 * 
 * @export
 * @interface HierarchyListResponse
 */
export interface HierarchyListResponse {
    /**
     * 
     * @type {Array<HierarchyNode>}
     * @memberof HierarchyListResponse
     */
    data?: Array<HierarchyNode>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof HierarchyListResponse
     */
    meta?: PaginationMeta;
}

/**
 * Check if a given object implements the HierarchyListResponse interface.
 */
export function instanceOfHierarchyListResponse(value: object): value is HierarchyListResponse {
    return true;
}

export function HierarchyListResponseFromJSON(json: any): HierarchyListResponse {
    return HierarchyListResponseFromJSONTyped(json, false);
}

export function HierarchyListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HierarchyListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(HierarchyNodeFromJSON)),
        'meta': json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
    };
}

export function HierarchyListResponseToJSON(json: any): HierarchyListResponse {
    return HierarchyListResponseToJSONTyped(json, false);
}

export function HierarchyListResponseToJSONTyped(value?: HierarchyListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(HierarchyNodeToJSON)),
        'meta': PaginationMetaToJSON(value['meta']),
    };
}

