/* tslint:disable */
/* eslint-disable */
/**
 * GeoAPI
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HierarchyNode
 */
export interface HierarchyNode {
    /**
     * 
     * @type {number}
     * @memberof HierarchyNode
     */
    geonameId?: number;
    /**
     * 
     * @type {string}
     * @memberof HierarchyNode
     */
    name?: string;
    /**
     * 
     * @type {HierarchyNodeTypeEnum}
     * @memberof HierarchyNode
     */
    type?: HierarchyNodeTypeEnum;
    /**
     * THE DIRECTION DEPENDS ON THE ENDPOINT, because this schema is shared by two operations that number their nodes from opposite ends.
     * 
     * On `GET /v1/cities/{id}/hierarchy` depth counts UP from the entity asked about: `depth: 0` is the city and the country carries the HIGHEST depth. On `GET /v1/resolve` depth is POSITIONAL, counting outward-in: `depth: 0` is the COUNTRY. Code that sorts or indexes on this field across both endpoints without accounting for the inversion silently REVERSES the hierarchy rather than failing — `max(by: depth)` returns the country on one and the innermost region on the other.
     * 
     * On `/v1/resolve` depth is the ARRAY INDEX and NOT an administrative level. A chain may skip a level: a measured 3.8% of coordinates resolve to a country plus a level-2 region with no level-1 region, and in those `depth: 1` is a level-2 area. `HierarchyNode` carries no `level` field, so there is no second signal to disambiguate with — treat depth as position only.
     * @type {number}
     * @memberof HierarchyNode
     */
    depth?: number;
}


/**
 * @export
 */
export const HierarchyNodeTypeEnum = {
    City: 'city',
    Region: 'region',
    Country: 'country',
    Continent: 'continent'
} as const;
export type HierarchyNodeTypeEnum = typeof HierarchyNodeTypeEnum[keyof typeof HierarchyNodeTypeEnum];


/**
 * Check if a given object implements the HierarchyNode interface.
 */
export function instanceOfHierarchyNode(value: object): value is HierarchyNode {
    return true;
}

export function HierarchyNodeFromJSON(json: any): HierarchyNode {
    return HierarchyNodeFromJSONTyped(json, false);
}

export function HierarchyNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): HierarchyNode {
    if (json == null) {
        return json;
    }
    return {
        
        'geonameId': json['geoname_id'] == null ? undefined : json['geoname_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'depth': json['depth'] == null ? undefined : json['depth'],
    };
}

export function HierarchyNodeToJSON(json: any): HierarchyNode {
    return HierarchyNodeToJSONTyped(json, false);
}

export function HierarchyNodeToJSONTyped(value?: HierarchyNode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'geoname_id': value['geonameId'],
        'name': value['name'],
        'type': value['type'],
        'depth': value['depth'],
    };
}

