/* tslint:disable */
/* eslint-disable */
/**
 * GeoAPI
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IPResultLocation
 */
export interface IPResultLocation {
    /**
     * 
     * @type {number}
     * @memberof IPResultLocation
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof IPResultLocation
     */
    longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof IPResultLocation
     */
    accuracyRadius?: number;
    /**
     * 
     * @type {string}
     * @memberof IPResultLocation
     */
    timezone?: string;
}

/**
 * Check if a given object implements the IPResultLocation interface.
 */
export function instanceOfIPResultLocation(value: object): value is IPResultLocation {
    return true;
}

export function IPResultLocationFromJSON(json: any): IPResultLocation {
    return IPResultLocationFromJSONTyped(json, false);
}

export function IPResultLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): IPResultLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'accuracyRadius': json['accuracy_radius'] == null ? undefined : json['accuracy_radius'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
    };
}

export function IPResultLocationToJSON(json: any): IPResultLocation {
    return IPResultLocationToJSONTyped(json, false);
}

export function IPResultLocationToJSONTyped(value?: IPResultLocation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'accuracy_radius': value['accuracyRadius'],
        'timezone': value['timezone'],
    };
}

