/* tslint:disable */
/* eslint-disable */
/**
 * GeoSearch
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: info@geosearch.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IPResultCountry } from './IPResultCountry';
import {
    IPResultCountryFromJSON,
    IPResultCountryFromJSONTyped,
    IPResultCountryToJSON,
    IPResultCountryToJSONTyped,
} from './IPResultCountry';
import type { IPResultPostal } from './IPResultPostal';
import {
    IPResultPostalFromJSON,
    IPResultPostalFromJSONTyped,
    IPResultPostalToJSON,
    IPResultPostalToJSONTyped,
} from './IPResultPostal';
import type { IPResultContinent } from './IPResultContinent';
import {
    IPResultContinentFromJSON,
    IPResultContinentFromJSONTyped,
    IPResultContinentToJSON,
    IPResultContinentToJSONTyped,
} from './IPResultContinent';
import type { IPResultLocation } from './IPResultLocation';
import {
    IPResultLocationFromJSON,
    IPResultLocationFromJSONTyped,
    IPResultLocationToJSON,
    IPResultLocationToJSONTyped,
} from './IPResultLocation';
import type { IPResultCity } from './IPResultCity';
import {
    IPResultCityFromJSON,
    IPResultCityFromJSONTyped,
    IPResultCityToJSON,
    IPResultCityToJSONTyped,
} from './IPResultCity';
import type { IPResultRegion } from './IPResultRegion';
import {
    IPResultRegionFromJSON,
    IPResultRegionFromJSONTyped,
    IPResultRegionToJSON,
    IPResultRegionToJSONTyped,
} from './IPResultRegion';

/**
 * 
 * @export
 * @interface IPResult
 */
export interface IPResult {
    /**
     * 
     * @type {string}
     * @memberof IPResult
     */
    ip?: string;
    /**
     * 
     * @type {string}
     * @memberof IPResult
     */
    network?: string;
    /**
     * 
     * @type {IPResultContinent}
     * @memberof IPResult
     */
    continent?: IPResultContinent;
    /**
     * 
     * @type {IPResultCountry}
     * @memberof IPResult
     */
    country?: IPResultCountry;
    /**
     * 
     * @type {IPResultRegion}
     * @memberof IPResult
     */
    region?: IPResultRegion;
    /**
     * 
     * @type {IPResultCity}
     * @memberof IPResult
     */
    city?: IPResultCity;
    /**
     * 
     * @type {IPResultPostal}
     * @memberof IPResult
     */
    postal?: IPResultPostal;
    /**
     * 
     * @type {IPResultLocation}
     * @memberof IPResult
     */
    location?: IPResultLocation;
    /**
     * 
     * @type {boolean}
     * @memberof IPResult
     */
    isAnonymousProxy?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IPResult
     */
    isSatelliteProvider?: boolean;
}

/**
 * Check if a given object implements the IPResult interface.
 */
export function instanceOfIPResult(value: object): value is IPResult {
    return true;
}

export function IPResultFromJSON(json: any): IPResult {
    return IPResultFromJSONTyped(json, false);
}

export function IPResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): IPResult {
    if (json == null) {
        return json;
    }
    return {
        
        'ip': json['ip'] == null ? undefined : json['ip'],
        'network': json['network'] == null ? undefined : json['network'],
        'continent': json['continent'] == null ? undefined : IPResultContinentFromJSON(json['continent']),
        'country': json['country'] == null ? undefined : IPResultCountryFromJSON(json['country']),
        'region': json['region'] == null ? undefined : IPResultRegionFromJSON(json['region']),
        'city': json['city'] == null ? undefined : IPResultCityFromJSON(json['city']),
        'postal': json['postal'] == null ? undefined : IPResultPostalFromJSON(json['postal']),
        'location': json['location'] == null ? undefined : IPResultLocationFromJSON(json['location']),
        'isAnonymousProxy': json['is_anonymous_proxy'] == null ? undefined : json['is_anonymous_proxy'],
        'isSatelliteProvider': json['is_satellite_provider'] == null ? undefined : json['is_satellite_provider'],
    };
}

export function IPResultToJSON(json: any): IPResult {
    return IPResultToJSONTyped(json, false);
}

export function IPResultToJSONTyped(value?: IPResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ip': value['ip'],
        'network': value['network'],
        'continent': IPResultContinentToJSON(value['continent']),
        'country': IPResultCountryToJSON(value['country']),
        'region': IPResultRegionToJSON(value['region']),
        'city': IPResultCityToJSON(value['city']),
        'postal': IPResultPostalToJSON(value['postal']),
        'location': IPResultLocationToJSON(value['location']),
        'is_anonymous_proxy': value['isAnonymousProxy'],
        'is_satellite_provider': value['isSatelliteProvider'],
    };
}

