/* tslint:disable */
/* eslint-disable */
/**
 * GeoSearch
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CountryRef } from './CountryRef';
import {
    CountryRefFromJSON,
    CountryRefFromJSONTyped,
    CountryRefToJSON,
    CountryRefToJSONTyped,
} from './CountryRef';
import type { RegionRef } from './RegionRef';
import {
    RegionRefFromJSON,
    RegionRefFromJSONTyped,
    RegionRefToJSON,
    RegionRefToJSONTyped,
} from './RegionRef';

/**
 * 
 * @export
 * @interface NearbyCity
 */
export interface NearbyCity {
    /**
     * 
     * @type {number}
     * @memberof NearbyCity
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof NearbyCity
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof NearbyCity
     */
    countryCode?: string;
    /**
     * 
     * @type {number}
     * @memberof NearbyCity
     */
    population?: number;
    /**
     * 
     * @type {string}
     * @memberof NearbyCity
     */
    timezone?: string;
    /**
     * 
     * @type {number}
     * @memberof NearbyCity
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof NearbyCity
     */
    longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof NearbyCity
     */
    distanceKm?: number;
    /**
     * 
     * @type {CountryRef}
     * @memberof NearbyCity
     */
    country?: CountryRef;
    /**
     * 
     * @type {RegionRef}
     * @memberof NearbyCity
     */
    region?: RegionRef;
}

/**
 * Check if a given object implements the NearbyCity interface.
 */
export function instanceOfNearbyCity(value: object): value is NearbyCity {
    return true;
}

export function NearbyCityFromJSON(json: any): NearbyCity {
    return NearbyCityFromJSONTyped(json, false);
}

export function NearbyCityFromJSONTyped(json: any, ignoreDiscriminator: boolean): NearbyCity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'countryCode': json['country_code'] == null ? undefined : json['country_code'],
        'population': json['population'] == null ? undefined : json['population'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'distanceKm': json['distance_km'] == null ? undefined : json['distance_km'],
        'country': json['country'] == null ? undefined : CountryRefFromJSON(json['country']),
        'region': json['region'] == null ? undefined : RegionRefFromJSON(json['region']),
    };
}

export function NearbyCityToJSON(json: any): NearbyCity {
    return NearbyCityToJSONTyped(json, false);
}

export function NearbyCityToJSONTyped(value?: NearbyCity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'country_code': value['countryCode'],
        'population': value['population'],
        'timezone': value['timezone'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'distance_km': value['distanceKm'],
        'country': CountryRefToJSON(value['country']),
        'region': RegionRefToJSON(value['region']),
    };
}

