/* tslint:disable */
/* eslint-disable */
/**
 * GeoAPI
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationMeta
 */
export interface PaginationMeta {
    /**
     * Cursor for the next page
     * @type {string}
     * @memberof PaginationMeta
     */
    nextCursor?: string;
    /**
     * Cursor for the previous page
     * @type {string}
     * @memberof PaginationMeta
     */
    prevCursor?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PaginationMeta
     */
    hasNext?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaginationMeta
     */
    hasPrev?: boolean;
    /**
     * Number of items in this response
     * @type {number}
     * @memberof PaginationMeta
     */
    count?: number;
}

/**
 * Check if a given object implements the PaginationMeta interface.
 */
export function instanceOfPaginationMeta(value: object): value is PaginationMeta {
    return true;
}

export function PaginationMetaFromJSON(json: any): PaginationMeta {
    return PaginationMetaFromJSONTyped(json, false);
}

export function PaginationMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
        'prevCursor': json['prev_cursor'] == null ? undefined : json['prev_cursor'],
        'hasNext': json['has_next'] == null ? undefined : json['has_next'],
        'hasPrev': json['has_prev'] == null ? undefined : json['has_prev'],
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function PaginationMetaToJSON(json: any): PaginationMeta {
    return PaginationMetaToJSONTyped(json, false);
}

export function PaginationMetaToJSONTyped(value?: PaginationMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'next_cursor': value['nextCursor'],
        'prev_cursor': value['prevCursor'],
        'has_next': value['hasNext'],
        'has_prev': value['hasPrev'],
        'count': value['count'],
    };
}

