/* tslint:disable */
/* eslint-disable */
/**
 * GeoAPI
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CountryRef } from './CountryRef';
import {
    CountryRefFromJSON,
    CountryRefFromJSONTyped,
    CountryRefToJSON,
    CountryRefToJSONTyped,
} from './CountryRef';

/**
 * 
 * @export
 * @interface PostalCode
 */
export interface PostalCode {
    /**
     * 
     * @type {number}
     * @memberof PostalCode
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PostalCode
     */
    countryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof PostalCode
     */
    postalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof PostalCode
     */
    placeName?: string;
    /**
     * 
     * @type {string}
     * @memberof PostalCode
     */
    adminName1?: string;
    /**
     * 
     * @type {string}
     * @memberof PostalCode
     */
    adminCode1?: string;
    /**
     * 
     * @type {string}
     * @memberof PostalCode
     */
    adminName2?: string;
    /**
     * 
     * @type {string}
     * @memberof PostalCode
     */
    adminCode2?: string;
    /**
     * 
     * @type {string}
     * @memberof PostalCode
     */
    adminName3?: string;
    /**
     * 
     * @type {string}
     * @memberof PostalCode
     */
    adminCode3?: string;
    /**
     * 
     * @type {number}
     * @memberof PostalCode
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof PostalCode
     */
    longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof PostalCode
     */
    accuracy?: number;
    /**
     * 
     * @type {CountryRef}
     * @memberof PostalCode
     */
    country?: CountryRef;
}

/**
 * Check if a given object implements the PostalCode interface.
 */
export function instanceOfPostalCode(value: object): value is PostalCode {
    return true;
}

export function PostalCodeFromJSON(json: any): PostalCode {
    return PostalCodeFromJSONTyped(json, false);
}

export function PostalCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostalCode {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'countryCode': json['country_code'] == null ? undefined : json['country_code'],
        'postalCode': json['postal_code'] == null ? undefined : json['postal_code'],
        'placeName': json['place_name'] == null ? undefined : json['place_name'],
        'adminName1': json['admin_name1'] == null ? undefined : json['admin_name1'],
        'adminCode1': json['admin_code1'] == null ? undefined : json['admin_code1'],
        'adminName2': json['admin_name2'] == null ? undefined : json['admin_name2'],
        'adminCode2': json['admin_code2'] == null ? undefined : json['admin_code2'],
        'adminName3': json['admin_name3'] == null ? undefined : json['admin_name3'],
        'adminCode3': json['admin_code3'] == null ? undefined : json['admin_code3'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'accuracy': json['accuracy'] == null ? undefined : json['accuracy'],
        'country': json['country'] == null ? undefined : CountryRefFromJSON(json['country']),
    };
}

export function PostalCodeToJSON(json: any): PostalCode {
    return PostalCodeToJSONTyped(json, false);
}

export function PostalCodeToJSONTyped(value?: PostalCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'country_code': value['countryCode'],
        'postal_code': value['postalCode'],
        'place_name': value['placeName'],
        'admin_name1': value['adminName1'],
        'admin_code1': value['adminCode1'],
        'admin_name2': value['adminName2'],
        'admin_code2': value['adminCode2'],
        'admin_name3': value['adminName3'],
        'admin_code3': value['adminCode3'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'accuracy': value['accuracy'],
        'country': CountryRefToJSON(value['country']),
    };
}

