/* tslint:disable */
/* eslint-disable */
/**
 * GeoSearch
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Structured detail accompanying a `quota_exceeded` 429. Present only on that response; absent from every other error body. It answers, in machine-readable form, what the limit is, how much was used, when it resets, and where to raise it — the same four facts `error.message` repeats in prose for the benefit of log lines and stack traces.
 * @export
 * @interface QuotaDetail
 */
export interface QuotaDetail {
    /**
     * Monthly request allowance for the account's current plan.
     * @type {number}
     * @memberof QuotaDetail
     */
    limit: number;
    /**
     * Requests consumed in the current quota period.
     * @type {number}
     * @memberof QuotaDetail
     */
    used: number;
    /**
     * Start of the next quota period, when `used` returns to zero. Matches the `X-RateLimit-Reset` header on the same response, expressed as RFC 3339 rather than an epoch second.
     * @type {Date}
     * @memberof QuotaDetail
     */
    resetsAt: Date;
    /**
     * Absolute URL of the billing page where the plan can be raised. Derived server-side from configuration and never reflected from a request header or parameter.
     * @type {string}
     * @memberof QuotaDetail
     */
    upgradeUrl: string;
}

/**
 * Check if a given object implements the QuotaDetail interface.
 */
export function instanceOfQuotaDetail(value: object): value is QuotaDetail {
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('used' in value) || value['used'] === undefined) return false;
    if (!('resetsAt' in value) || value['resetsAt'] === undefined) return false;
    if (!('upgradeUrl' in value) || value['upgradeUrl'] === undefined) return false;
    return true;
}

export function QuotaDetailFromJSON(json: any): QuotaDetail {
    return QuotaDetailFromJSONTyped(json, false);
}

export function QuotaDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuotaDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'],
        'used': json['used'],
        'resetsAt': (new Date(json['resets_at'])),
        'upgradeUrl': json['upgrade_url'],
    };
}

export function QuotaDetailToJSON(json: any): QuotaDetail {
    return QuotaDetailToJSONTyped(json, false);
}

export function QuotaDetailToJSONTyped(value?: QuotaDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'used': value['used'],
        'resets_at': value['resetsAt'].toISOString(),
        'upgrade_url': value['upgradeUrl'],
    };
}

