/* tslint:disable */
/* eslint-disable */
/**
 * GeoAPI
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CountryRef } from './CountryRef';
import {
    CountryRefFromJSON,
    CountryRefFromJSONTyped,
    CountryRefToJSON,
    CountryRefToJSONTyped,
} from './CountryRef';
import type { GeoJSONMultiPolygon } from './GeoJSONMultiPolygon';
import {
    GeoJSONMultiPolygonFromJSON,
    GeoJSONMultiPolygonFromJSONTyped,
    GeoJSONMultiPolygonToJSON,
    GeoJSONMultiPolygonToJSONTyped,
} from './GeoJSONMultiPolygon';

/**
 * 
 * @export
 * @interface Region
 */
export interface Region {
    /**
     * 
     * @type {number}
     * @memberof Region
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Region
     */
    geonameId?: number;
    /**
     * 
     * @type {string}
     * @memberof Region
     */
    countryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Region
     */
    adminCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Region
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Region
     */
    asciiName?: string;
    /**
     * 
     * @type {number}
     * @memberof Region
     */
    level?: number;
    /**
     * 
     * @type {number}
     * @memberof Region
     */
    parentGeonameId?: number;
    /**
     * 
     * @type {number}
     * @memberof Region
     */
    population?: number;
    /**
     * 
     * @type {number}
     * @memberof Region
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof Region
     */
    longitude?: number;
    /**
     * 
     * @type {CountryRef}
     * @memberof Region
     */
    country?: CountryRef;
    /**
     * Region boundary. Returned by default on `GET /v1/regions/{id}`, and on request via `?fields=geometry` on `GET /v1/regions` and `GET /v1/countries/{code}/regions`.
     * 
     * REQUIRES A PAID PLAN. On all three of those routes this key is OMITTED ENTIRELY for a Free-tier key — absent, not null, with a 200 status and no error. A client reading `data.geometry.type` unconditionally will fail on a null dereference.
     * 
     * To be told explicitly rather than silently, request the polygon from `GET /v1/boundaries/{geoname_id}`, which answers a Free key with a 403 and an upgrade link.
     * @type {GeoJSONMultiPolygon}
     * @memberof Region
     */
    geometry?: GeoJSONMultiPolygon;
}

/**
 * Check if a given object implements the Region interface.
 */
export function instanceOfRegion(value: object): value is Region {
    return true;
}

export function RegionFromJSON(json: any): Region {
    return RegionFromJSONTyped(json, false);
}

export function RegionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Region {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'geonameId': json['geoname_id'] == null ? undefined : json['geoname_id'],
        'countryCode': json['country_code'] == null ? undefined : json['country_code'],
        'adminCode': json['admin_code'] == null ? undefined : json['admin_code'],
        'name': json['name'] == null ? undefined : json['name'],
        'asciiName': json['ascii_name'] == null ? undefined : json['ascii_name'],
        'level': json['level'] == null ? undefined : json['level'],
        'parentGeonameId': json['parent_geoname_id'] == null ? undefined : json['parent_geoname_id'],
        'population': json['population'] == null ? undefined : json['population'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'country': json['country'] == null ? undefined : CountryRefFromJSON(json['country']),
        'geometry': json['geometry'] == null ? undefined : GeoJSONMultiPolygonFromJSON(json['geometry']),
    };
}

export function RegionToJSON(json: any): Region {
    return RegionToJSONTyped(json, false);
}

export function RegionToJSONTyped(value?: Region | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'geoname_id': value['geonameId'],
        'country_code': value['countryCode'],
        'admin_code': value['adminCode'],
        'name': value['name'],
        'ascii_name': value['asciiName'],
        'level': value['level'],
        'parent_geoname_id': value['parentGeonameId'],
        'population': value['population'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'country': CountryRefToJSON(value['country']),
        'geometry': GeoJSONMultiPolygonToJSON(value['geometry']),
    };
}

