/* tslint:disable */
/* eslint-disable */
/**
 * GeoAPI
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan\'s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan\'s quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Structured detail accompanying a `tier_upgrade_required` 403. Present only on that response; absent from every other error body.
 * 
 * ONE FIELD, DELIBERATELY. It says where to go and claims nothing else. It carries no limit, no usage and no reset instant, because none of those describe a plan that simply does not include the feature — there is no quantity to wait for and nothing resets.
 * @export
 * @interface UpgradeDetail
 */
export interface UpgradeDetail {
    /**
     * Absolute URL of the billing page where the plan can be raised. Derived server-side from configuration and never reflected from a request header or parameter.
     * @type {string}
     * @memberof UpgradeDetail
     */
    upgradeUrl: string;
}

/**
 * Check if a given object implements the UpgradeDetail interface.
 */
export function instanceOfUpgradeDetail(value: object): value is UpgradeDetail {
    if (!('upgradeUrl' in value) || value['upgradeUrl'] === undefined) return false;
    return true;
}

export function UpgradeDetailFromJSON(json: any): UpgradeDetail {
    return UpgradeDetailFromJSONTyped(json, false);
}

export function UpgradeDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpgradeDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'upgradeUrl': json['upgrade_url'],
    };
}

export function UpgradeDetailToJSON(json: any): UpgradeDetail {
    return UpgradeDetailToJSONTyped(json, false);
}

export function UpgradeDetailToJSONTyped(value?: UpgradeDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'upgrade_url': value['upgradeUrl'],
    };
}

